In [3]:
import numpy as np

def gaussnaive(A,b):
    """
    gaussnaive: naive Gauss elimination
    input:
    A = coefficient matrix
    b = constant vector
    output:
    x = solution vector
    """
    (n,m) = A.shape
    if n != m:
       return 'Coefficient matrix A must be square'
    nb = n+1
    # build augmented matrix
    Aug = np.hstack((A,b))
    print(Aug)
    # forward elimination
    for k in range(n-1):
      for i in range(k+1,n):
        factor = Aug[i,k]/Aug[k,k]
        Aug[i,k:nb] = Aug[i,k:nb]-factor*Aug[k,k:nb]
    # back substitution
    x = np.zeros([n,1]) # create empty x array
    x = np.matrix(x) # convert to matrix type
    x[n-1] = Aug[n-1,nb-1]/Aug[n-1,n-1]
    for i in range(n-2,-1,-1):
        x[i] = (Aug[i,nb-1]-Aug[i,i+1:n]*x[i+1:n,0])/Aug[i,i]
    return x


In [4]:
A = np.matrix('4 -2 1 ; 1 1 1 ; 9 3 1', dtype=np.float64)
b = np.matrix('8; -13; 3')
gaussnaive(A,b)

[[  4.  -2.   1.   8.]
 [  1.   1.   1. -13.]
 [  9.   3.   1.   3.]]


matrix([[  3.],
        [ -4.],
        [-12.]])